#!/usr/bin/env python3
"""Render a proof-of-concept demo of dynamic text effects with libass.

This is a documentation artifact, not part of the app: it shows what the
final MP4 would look like when text effects are rendered through the `ass`
filter (libass) — the engine already compiled into the custom FFmpeg build
(`--enable-libass`). Each demo segment maps to an effect family from
docs/text-effects-options.md and prints the ASS tags it uses.

Run from this directory (any FFmpeg with libass works — Debian's, the
imageio-ffmpeg static build, or the custom 8.1.2 container build):

    python3 make_text_effects_demo.py
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

FPS = 25
W, H = 1280, 720
SEGMENT = 3.0            # seconds per demo
FONT_DIR = Path(__file__).resolve().parents[1] / "public" / "fonts"
FONT = "Montserrat Bold"  # family name inside public/fonts/Montserrat-Bold.ttf


def ts(seconds: float) -> str:
    cs = round(seconds * 100)
    return f"{cs // 360000}:{cs // 6000 % 60:02d}:{cs // 100 % 60:02d}.{cs % 100:02d}"


def header() -> str:
    return f"""[Script Info]
; Dynamic text effects demo — generated by make_text_effects_demo.py
ScriptType: v4.00+
PlayResX: {W}
PlayResY: {H}
ScaledBorderAndShadow: yes
WrapStyle: 2

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: FX,{FONT},86,&H00FFFFFF,&H00909090,&H00202418,&H80000000,0,0,0,0,100,100,0,0,1,3,2,5,60,60,40,1
Style: Label,{FONT},24,&H00C9CCBF,&H000000FF,&H00202418,&H80000000,1,0,0,0,100,100,0,0,1,1,0,7,24,24,20,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"""


def label(name: str, tags: str, start: float) -> str:
    """Top-left caption naming the effect and the tags that build it."""
    return f"Dialogue: 9,{ts(start)},{ts(start + SEGMENT)},Label,,0,0,0,,{{\\fad(150,150)}}{name}  —  {tags}"


def centered(text: str, start: float, end: float, tags: str) -> str:
    return f"Dialogue: 0,{ts(start)},{ts(end)},FX,,0,0,0,,{{{tags}}}{text}"


def seg_pop(s: float) -> list[str]:
    # Enter: scale overshoot then settle (fontsize itself is static; the
    # transform tags scale the rendered glyphs).
    tags = r"\fscx20\fscy20\t(0,220,\fscx118\fscy118)\t(220,420,\fscx100\fscy100)\fad(120,160)"
    return [label("Pop (enter)", r"\fscx/\fscy overshoot + \fad", s),
            centered("Pop!", s, s + SEGMENT, tags)]


def seg_bounce(s: float) -> list[str]:
    # Enter: real damped bounce. libass cannot chain \move, so the demo uses
    # per-frame events with an explicit \pos — the "anything is possible" tier.
    events = [label("Bounce (enter)", r"per-frame \pos events (damped bounce)", s)]
    target = int(H * 0.52)
    fall_t = 0.55          # drop duration
    bounces = [(40, 0.30), (16, 0.22), (6, 0.16)]  # (height, duration)
    t = s
    y = -80.0
    vy = 0.0
    frame = 1 / FPS
    # Simple ballistic fall + damped bounces, one \pos event per frame.
    positions: list[tuple[float, float]] = []
    v = 0.0
    remaining = fall_t
    while remaining > 0:
        step = min(frame, remaining)
        v += 2600 * step          # gravity-ish
        y += v * step
        if y >= target:
            y, v = float(target), 0.0
            break
        positions.append((t, y))
        t += step
        remaining -= step
    positions.append((t, y))
    for peak, dur in bounces:
        v = (2 * 2600 * peak) ** 0.5
        remaining = dur / 2
        while remaining > 0:
            step = min(frame, remaining)
            v -= 2600 * step
            y -= v * step
            positions.append((t, max(0.0, y)))
            t += step
            remaining -= step
        remaining = dur / 2
        while remaining > 0:
            step = min(frame, remaining)
            v += 2600 * step
            y += v * step
            if y >= target:
                y = float(target)
            positions.append((t, y))
            t += step
            remaining -= step
        y = float(target)
    positions.append((t, y))
    for i, (when, why) in enumerate(positions):
        end = positions[i + 1][0] if i + 1 < len(positions) else s + SEGMENT
        events.append(f"Dialogue: 0,{ts(when)},{ts(min(end, s + SEGMENT))},FX,,0,0,0,,{{\\pos({W // 2},{int(why)})}}Bounce!")
    return events


def seg_glow(s: float) -> list[str]:
    # While shown: coloured outline whose blur breathes (chained \t loop).
    tags = r"\bord3\3c&H3C905F&\t(0,700,\blur7)\t(700,1400,\blur1)\t(1400,2100,\blur7)\t(2100,2800,\blur1)"
    return [label("Glow (while shown)", r"\bord + coloured \3c + breathing \blur", s),
            centered("Glow", s, s + SEGMENT, tags)]


def seg_typewriter(s: float) -> list[str]:
    # Enter: karaoke tags reveal one character at a time.
    text = "Every letter lands"
    karaoke = "".join(f"{{\\k18}}{char}" for char in text)
    return [label("Typewriter (enter)", r"karaoke \k per character", s),
            centered(karaoke, s, s + SEGMENT, r"\fad(0,150)")]


def seg_blur_in(s: float) -> list[str]:
    tags = r"\blur9\alpha&HFF&\t(0,550,\blur0\alpha&H00&)"
    return [label("Blur-in (enter)", r"\blur + \alpha animated by \t", s),
            centered("Sharp", s, s + SEGMENT, tags)]


def seg_pulse(s: float) -> list[str]:
    tags = r"\t(0,600,\fscx109\fscy109)\t(600,1200,\fscx100\fscy100)\t(1200,1800,\fscx109\fscy109)\t(1800,2400,\fscx100\fscy100)"
    return [label("Pulse (while shown)", r"chained \t scale loop", s),
            centered("Pulse", s, s + SEGMENT, tags)]


def seg_split(s: float) -> list[str]:
    # Enter: per-character events rise into place with a stagger.
    text = "Split stagger"
    events = [label("Split stagger (enter)", r"one event per character, staggered \move", s)]
    width = 62
    total = len(text) * width
    x = (W - total) // 2 + width // 2
    for i, char in enumerate(text):
        start = s + i * 0.07
        shown = char if char != " " else "\\N"
        events.append(
            f"Dialogue: 0,{ts(start)},{ts(s + SEGMENT)},FX,,0,0,0,,"
            f"{{\\pos({x + i * width},{int(H * 0.52)})\\move({x + i * width},{int(H * 0.52) + 46},{x + i * width},{int(H * 0.52)},0,320)\\fad(90,0)}}{shown}")
    return events


def seg_shake(s: float) -> list[str]:
    # While shown: impact shake, decaying jitter from per-frame events.
    import random
    random.seed(7)
    events = [label("Shake (while shown)", r"per-frame \pos jitter, decaying", s)]
    y0 = int(H * 0.52)
    when = s
    for i in range(int(0.9 * FPS)):
        amp = 16 * (1 - i / (0.9 * FPS)) ** 2
        dx = random.randint(-int(amp), int(amp))
        dy = random.randint(-int(amp), int(amp))
        events.append(f"Dialogue: 0,{ts(when)},{ts(when + 1 / FPS)},FX,,0,0,0,,{{\\pos({W // 2 + dx},{y0 + dy})}}Shake!")
        when += 1 / FPS
    events.append(centered("Shake!", when, s + SEGMENT, rf"\pos({W // 2},{y0})"))
    return events


def seg_exit(s: float) -> list[str]:
    # Exit: scale up + fade out at the end of the hold.
    tags = rf"\t({int(SEGMENT * 1000) - 500},{int(SEGMENT * 1000) - 120},\fscx132\fscy132\alpha&HFF&)""\fad(150,0)"
    return [label("Pop-out (exit)", r"delayed \t scale + \alpha out", s),
            centered("Goodbye", s, s + SEGMENT, tags)]


def build_ass() -> str:
    lines = [header()]
    segs = [seg_pop, seg_bounce, seg_glow, seg_typewriter, seg_blur_in, seg_pulse, seg_split, seg_shake, seg_exit]
    for index, seg in enumerate(segs):
        lines.extend(str(event) for event in seg(index * SEGMENT))
    return "\n".join(lines) + "\n"


def main() -> None:
    here = Path(__file__).parent
    ass_path = here / "text-effects-demo.ass"
    mp4_path = here / "text-effects-demo.mp4"
    poster_path = here / "text-effects-poster.png"
    ass_path.write_text(build_ass(), encoding="utf-8")

    total = SEGMENT * 9
    subprocess.run([
        "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
        "-f", "lavfi", "-i", f"color=c=0x171A15:s={W}x{H}:r={FPS}",
        "-vf", f"ass={ass_path.name}:fontsdir={FONT_DIR},vignette=PI/5",
        "-t", str(total), "-c:v", "libx264", "-crf", "20", "-pix_fmt", "yuv420p",
        str(mp4_path),
    ], cwd=here, check=True)

    # A 3×3 contact sheet so the doc can show everything at a glance.
    subprocess.run([
        "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
        "-i", str(mp4_path),
        "-vf", "select='eq(n\\,37)+eq(n\\,112)+eq(n\\,187)+eq(n\\,262)+eq(n\\,337)+eq(n\\,412)+eq(n\\,487)+eq(n\\,562)+eq(n\\,637)',scale=426:240,tile=3x3",
        "-frames:v", "1", str(poster_path),
    ], check=True)

    print(f"wrote {mp4_path} ({mp4_path.stat().st_size / 1e6:.1f} MB) and {poster_path}")


if __name__ == "__main__":
    sys.exit(main())
