"""The bundled caption fonts, read from ``registry/fonts.json``.

The same catalogue drives the browser (``src/fonts.ts`` / ``src/fonts.css``)
and the renderer, so a family offered in the editor always resolves to the file
FFmpeg draws with. The JSON is generated by ``scripts/build_fonts.py`` from the
files in ``public/fonts`` (copied to ``FONTS_DIR`` in the image).

Besides the file per style it carries the vertical metrics the text engines
need: libass sizes a font so that ``usWinAscent + usWinDescent`` equals the ASS
font size, CSS (and drawtext) so that the em square equals it. The stackable
engine (``text_motion.py``) converts with these numbers, so a caption has the
same size in the preview, in drawtext and in libass.
"""
from __future__ import annotations

import json
import logging
import os
import re
from functools import lru_cache
from pathlib import Path
from typing import Any

log = logging.getLogger(__name__)

STYLES = ("Regular", "Bold", "Italic", "BoldItalic")

# Used when the registry cannot be read (a stripped-down checkout): the
# historic families, so renders keep working.
_FALLBACK: dict[str, dict[str, str]] = {
    name: {style: f"{stem}-{style}.ttf" for style in styles}
    for name, stem, styles in [
        ("Montserrat", "Montserrat", STYLES), ("Open Sans", "OpenSans", STYLES), ("Roboto", "Roboto", STYLES),
        ("Lato", "Lato", STYLES), ("Poppins", "Poppins", STYLES), ("Raleway", "Raleway", STYLES),
        ("Nunito", "Nunito", STYLES), ("Source Sans 3", "SourceSans3", STYLES), ("Oswald", "Oswald", ("Regular", "Bold")),
        ("Playfair Display", "PlayfairDisplay", STYLES), ("Merriweather", "Merriweather", STYLES),
        ("Lora", "Lora", STYLES), ("Cormorant Garamond", "CormorantGaramond", STYLES),
        ("Bebas Neue", "BebasNeue", ("Regular",)), ("Anton", "Anton", ("Regular",)),
        ("Pacifico", "Pacifico", ("Regular",)), ("Dancing Script", "DancingScript", ("Regular", "Bold")),
        ("Caveat", "Caveat", ("Regular", "Bold")), ("Great Vibes", "GreatVibes", ("Regular",)),
    ]
}


def _candidates() -> list[Path]:
    cands: list[Path] = []
    env = os.environ.get("SLIDESHOW_FONT_REGISTRY")
    if env:
        cands.append(Path(env))
    here = Path(__file__).resolve()
    cands.append(here.parents[2] / "registry" / "fonts.json")
    cands.append(Path("/app/registry/fonts.json"))
    cands.append(Path.cwd() / "registry" / "fonts.json")
    return cands


@lru_cache(maxsize=1)
def font_registry() -> dict[str, Any]:
    for path in _candidates():
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        if isinstance(data, dict) and isinstance(data.get("families"), list):
            return data
    log.warning("registry/fonts.json not found; using the built-in font list")
    return {"families": [{"family": k, "group": "Sans", "files": v, "metrics": {}} for k, v in _FALLBACK.items()]}


def _key(name: str) -> str:
    return re.sub(r"\s+", "", str(name or "")).lower()


@lru_cache(maxsize=1)
def _by_key() -> dict[str, dict[str, Any]]:
    return {_key(entry.get("family", "")): entry for entry in font_registry()["families"] if entry.get("family")}


def font_files() -> dict[str, dict[str, str]]:
    """family -> {style: file name}, bundled families only."""
    return {entry["family"]: dict(entry.get("files") or {}) for entry in font_registry()["families"]
            if entry.get("files")}


def family_entry(family: str) -> dict[str, Any] | None:
    """Registry entry for a family name (case and spaces ignored)."""
    return _by_key().get(_key(family))


def style_name(bold: bool, italic: bool) -> str:
    return ("Bold" if bold else "") + ("Italic" if italic else "") or "Regular"


def available_style(family: str, bold: bool, italic: bool) -> tuple[bool, bool]:
    """The (bold, italic) the bundled files can really show.

    A family without a bold or italic cut is drawn upright / regular in every
    engine: the editor disables the toggle, drawtext falls back to the upright
    file and libass must not synthesise a faux bold or slant the browser would
    not show either.
    """
    entry = family_entry(family)
    files = (entry or {}).get("files") or {}
    if not files:
        return bold, italic
    has_bold = "Bold" in files or "BoldItalic" in files
    has_italic = "Italic" in files or "BoldItalic" in files
    return bold and has_bold, italic and has_italic


def font_metrics(family: str, bold: bool = False, italic: bool = False) -> dict[str, Any] | None:
    """Vertical metrics (font units) of the file that draws this style."""
    entry = family_entry(family)
    if not entry:
        return None
    metrics = entry.get("metrics") or {}
    order = {
        "Regular": ["Regular", "Bold"], "Bold": ["Bold", "Regular"],
        "Italic": ["Italic", "Regular", "BoldItalic", "Bold"],
        "BoldItalic": ["BoldItalic", "Bold", "Italic", "Regular"],
    }[style_name(bold, italic)]
    for style in order:
        if style in metrics:
            return metrics[style]
    return None


def font_path(family: str, bold: bool, italic: bool, fonts_dir: Path) -> Path | None:
    """Bundled file for the style (falling back within the family), or None."""
    entry = family_entry(family)
    files = (entry or {}).get("files") or {}
    order = {
        "Regular": ["Regular", "Bold"], "Bold": ["Bold", "Regular"],
        "Italic": ["Italic", "Regular", "BoldItalic", "Bold"],
        "BoldItalic": ["BoldItalic", "Bold", "Italic", "Regular"],
    }[style_name(bold, italic)]
    for style in order:
        name = files.get(style)
        if name and (Path(fonts_dir) / name).exists():
            return Path(fonts_dir) / name
    return None
