// The bundled caption fonts — one catalogue for the font picker, the preview
// and the renderer.
//
// registry/fonts.json is generated by scripts/build_fonts.py from the files in
// public/fonts (served at /fonts, copied to /app/fonts for FFmpeg), so every
// family the editor offers resolves to the exact file libass/drawtext draws
// with. backend/app/font_registry.py reads the same JSON.

import fontRegistry from '../registry/fonts.json'

export interface FontMetrics {
  upm: number
  winAscent: number
  winDescent: number
  hheaAscent: number
  hheaDescent: number
  typoAscent: number
  typoDescent: number
  typoLineGap: number
  useTypo: boolean
  weight: number
  italic: boolean
  capHeight: number
  xHeight: number
}

export interface FontEntry {
  family: string
  group: string
  licence: string
  source?: string
  tags: string[]
  system?: boolean
  files: Partial<Record<'Regular' | 'Bold' | 'Italic' | 'BoldItalic', string>>
  metrics?: Partial<Record<'Regular' | 'Bold' | 'Italic' | 'BoldItalic', FontMetrics>>
}

const registry = fontRegistry as unknown as { groups: string[]; families: FontEntry[] }

export const FONT_ENTRIES: FontEntry[] = registry.families
const BY_NAME = new Map(FONT_ENTRIES.map(entry => [entry.family.replace(/\s+/g, '').toLowerCase(), entry]))

/** Picker groups in display order: Sans, Serif, Display, Handwriting, Script, Typewriter. */
export const FONT_GROUPS: Record<string, string[]> = {}
for (const group of registry.groups) FONT_GROUPS[group] = []
for (const entry of FONT_ENTRIES) (FONT_GROUPS[entry.group] = FONT_GROUPS[entry.group] || []).push(entry.family)

export const FONT_FAMILIES = FONT_ENTRIES.map(entry => entry.family)

export const GROUP_HINTS: Record<string, string> = {
  Sans: 'Clean, neutral captions',
  Serif: 'Classic, editorial',
  Display: 'Tall headlines',
  Handwriting: 'Casual, hand-lettered — pairs with Write on',
  Script: 'Connected script & calligraphy',
  Typewriter: 'Typed, monospaced — pairs with Typewriter',
}

export function fontEntry(family: string): FontEntry | undefined {
  return BY_NAME.get(String(family || '').replace(/\s+/g, '').toLowerCase())
}

function hasStyle(entry: FontEntry | undefined, styles: string[]) {
  if (!entry || entry.system || !Object.keys(entry.files).length) return true
  return styles.some(style => style in entry.files)
}

/** Families with no italic cut: the toggle is disabled, FFmpeg draws upright. */
export const FONTS_WITHOUT_ITALIC = new Set(FONT_ENTRIES.filter(e => !hasStyle(e, ['Italic', 'BoldItalic'])).map(e => e.family))
/** Families with a single weight: bold would be a browser-only faux bold. */
export const FONTS_WITHOUT_BOLD = new Set(FONT_ENTRIES.filter(e => !hasStyle(e, ['Bold', 'BoldItalic'])).map(e => e.family))

/** The weight/slant the bundled files can really show (no synthesis anywhere). */
export function effectiveFontStyle(family: string, bold: boolean, italic: boolean) {
  return { bold: bold && !FONTS_WITHOUT_BOLD.has(family), italic: italic && !FONTS_WITHOUT_ITALIC.has(family) }
}

const DEFAULT_METRICS: FontMetrics = { upm: 1000, winAscent: 1000, winDescent: 250, hheaAscent: 900, hheaDescent: -250, typoAscent: 900, typoDescent: -250, typoLineGap: 0, useTypo: false, weight: 400, italic: false, capHeight: 700, xHeight: 500 }

/** Vertical metrics of the file that draws this style (font units). */
export function fontMetrics(family: string, bold: boolean, italic: boolean): FontMetrics {
  const entry = fontEntry(family)
  const metrics = entry?.metrics || {}
  const order = bold && italic ? ['BoldItalic', 'Bold', 'Italic', 'Regular'] : bold ? ['Bold', 'Regular'] : italic ? ['Italic', 'Regular', 'BoldItalic', 'Bold'] : ['Regular', 'Bold']
  for (const style of order) {
    const m = (metrics as Record<string, FontMetrics | undefined>)[style]
    if (m) return m
  }
  return DEFAULT_METRICS
}

/** CSS font-family stack for a caption family. */
export function fontStack(family: string) {
  const entry = fontEntry(family)
  const fallback = entry?.group === 'Serif' ? 'serif' : entry?.group === 'Typewriter' ? 'monospace' : entry?.group === 'Handwriting' || entry?.group === 'Script' ? 'cursive' : 'sans-serif'
  return `'${family}', ${fallback}`
}
